apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: uday-tomcat
  name: udaylb1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: uday-tomcat
  type: LoadBalancer
status:
  loadBalancer: {}
